### ISSUE TITLE
Deal with plans when branching

### ISSUE THREAD

**Issue by LogicalDash** [LogicalDash/LiSE#62]
Currently, when you create a new branch, it starts with the state of the world at the present moment, and doesn't include anything in the future. That seems logical, but that future might contain plans, such as travel plans, which will no longer be followed in the new branch. You could write your rules to immediately find a new path, but what if the map has changed since the initial plan? Your simulation will behave differently entirely because of when you chose to make a branch in the timestream.

Travel plans are the only kinds of plans I've yet implemented and tested, but any kind of plan could exist; I was thinking of plans as a scripting tool. It's not a very useful scripting tool, though, if it stops working when you branch the timestream. People are meant to branch the timestream whenever they feel like it. It's like saving your game. So plans really need to be brought over to the new branch.

The easy case is when you're at the very beginning of the planned part of the current branch and you make a new branch. Then, I can just copy the whole future of the old branch into the new one. But what if you rewind time to where it's already been simulated some, and branch there? I can't just copy the entire future because it contains a lot of events that may not occur in the new branch, as a result of changes you're about to make. I only want to copy the parts that had been part of the plan, until simulation happened.

That means I need to continue distinguishing planned events from regular ones, even after the simulation has gone past them and they've officially happened. The user might want to change or delete a plan in a branch, so I think I have to actually copy the whole future plan into each new branch, rather than contrive to look up the parent branches' plans from the child branch.

**Comment by LogicalDash** [comment]
But I don't just want to copy the entire future plan whenever there's a branch, because there might be some plans that were made as a *result* of actual simulation events that haven't happened yet in the new branch. Example: there's a random encounter and your character runs away from it. But then you rewind to before the random encounter, branch the timestream, and stay in a safe zone, so it doesn't happen. Running away created a travel plan, and that shouldn't be copied into the new branch, or else your character will appear to teleport to where they're running away from a dangerous event that didn't even happen this time.

I need a way to tell when a plan was created, and when the timestream branches, I need to copy plans that had been created at that time into the new branch.

Alternatively I could remove the whole concept of plans from the world model, and make it easy for users to implement their own, by storing a thing's travel plan on a stat of it and having a method to be called in an action that makes the thing take the next step on that path. But that will likely result in a bunch of mutually incompatible implementations of common travel behaviors, and any use of the planning system for scripting is out of the question.

**Comment by MrPetovan** [comment]
> I need a way to tell when a plan was created, and when the timestream branches, I need to copy plans that had been created at that time into the new branch.

This makes the most sense to me.

**Comment by LogicalDash** [comment]
I think what I'm going to end up doing is:

Each ``with engine.planning():`` block will create its own plan with a unique ID and a time of creation (a branch, turn, and tick). Branches created any time between the time of creation and the end of that plan will have the plan copied into them automatically. Branches created at any other time will not.

Contradicting a plan will cause the remainder of *that specific* plan to be erased, but plans made in any other ``with engine.planning():`` block will be left in place.

**Comment by LogicalDash** [comment]
I didn't make a proper pull request for it, but this was implemented in the "branchplan" branch, now merged.
